# See https://github.com/excelwebzone/EWZRecaptchaBundle for full configuration
ewz_recaptcha:
    public_key:  '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
    private_key: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
